### Mod properties
mod.name="Auto Share"
mod.id="auto_share"
mod.version="1.0"
mod.description="Automatically shares resource packs over LAN with no manual installation"

### Publishing
mod.modrinth="1VP93HJF"
mod.curseforge="1589837"
mod.github="auto-share"

### Subprojects
["26.1.2"]
pub-end="latest"

["1.21.1"]
pub-end="1.21.11"

["1.21.1-fabric"]
pub-start="1.20.5"
